"""
plain_text_formatter.py  v1.0.0
────────────────────────────────────────────────────────────────────────────
Plain-Text Clinical Report Formatter

Transforms AI Test Advisor response data into a print-optimized plain-text
document suitable for clinical documentation and printing.

Design principles:
  • Plain text output with clear section markers
  • Black-on-white print conventions (conceptual)
  • No markdown except simple section labeling
  • Graceful handling of missing data fields
  • Page-break markers for multi-page content
  • Clinical accuracy preservation (no content alteration)
  • Professional formatting appropriate for medical records

Output structure:
  1. Header (centered-style text)
  2. Query (quoted)
  3. Recommended Tests (numbered list)
  4. Clinical Rationale (rewritten paragraphs)
  5. Reference Sources (numbered citations)
  6. Footer (confidence, disclaimer, page number)
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any


# ── Constants ──────────────────────────────────────────────────────────────────

DISCLAIMER_TEXT = (
    "This recommendation is generated by an AI assistant using ARUP Laboratories "
    "reference materials. It is intended for informational purposes only and does "
    "not constitute medical advice. Final test selection decisions should be made "
    "by qualified healthcare professionals based on complete clinical context."
)

# Page width for text wrapping (characters)
PAGE_WIDTH = 80

# Estimated lines per page (conservative for page-break decisions)
LINES_PER_PAGE = 55


# ── Helper Functions ───────────────────────────────────────────────────────────

def _center_text(text: str, width: int = PAGE_WIDTH) -> str:
    """Center text within specified width."""
    padding = max(0, (width - len(text)) // 2)
    return ' ' * padding + text


def _wrap_text(text: str, width: int = PAGE_WIDTH, indent: int = 0) -> list[str]:
    """
    Wrap text to specified width with optional indentation.
    Preserves paragraph breaks (double newlines).
    """
    lines = []
    paragraphs = text.split('\n\n')

    for para in paragraphs:
        # Clean the paragraph text
        para = para.strip()
        if not para:
            continue

        # Split into words
        words = para.split()
        current_line = ' ' * indent

        for word in words:
            # Check if adding word would exceed width
            test_line = current_line + (' ' if current_line.strip() else '') + word
            if len(test_line) <= width:
                current_line = test_line
            else:
                # Line is full, start new line
                if current_line.strip():
                    lines.append(current_line)
                current_line = ' ' * indent + word

        # Add final line of paragraph
        if current_line.strip():
            lines.append(current_line)

        # Add blank line between paragraphs
        lines.append('')

    # Remove trailing blank line
    while lines and not lines[-1].strip():
        lines.pop()

    return lines


def _strip_markdown(text: str) -> str:
    """
    Remove markdown formatting and hyperlinks while preserving text content.
    Converts citation markers [SOURCE N] to plain parenthetical references.
    """
    if not text:
        return ""

    # Remove markdown links [text](url) → text
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)

    # Convert citation markers [SOURCE N] to (Ref N)
    text = re.sub(r'\[SOURCE (\d+)\]', r'(Ref \1)', text)

    # Remove bold/italic markers
    text = re.sub(r'\*\*([^\*]+)\*\*', r'\1', text)  # **bold**
    text = re.sub(r'\*([^\*]+)\*', r'\1', text)      # *italic*
    text = re.sub(r'__([^_]+)__', r'\1', text)       # __bold__
    text = re.sub(r'_([^_]+)_', r'\1', text)         # _italic_

    # Remove code markers
    text = re.sub(r'`([^`]+)`', r'\1', text)

    # Remove headers (## Header → Header)
    text = re.sub(r'^#+\s+', '', text, flags=re.MULTILINE)

    return text.strip()


def _depersonalize_text(text: str) -> str:
    """
    Remove conversational and first-person phrasing while preserving clinical meaning.
    Converts casual language to professional clinical documentation style.
    """
    if not text:
        return ""

    # Remove conversational openings
    text = re.sub(r'^(Based on|According to|In response to|To answer)\s+', '', text, flags=re.IGNORECASE)

    # Remove first-person references
    text = re.sub(r'\bI (recommend|suggest|would|can|will)\b', 'This analysis recommends', text, flags=re.IGNORECASE)
    text = re.sub(r'\bmy (recommendation|suggestion|analysis)\b', 'The recommendation', text, flags=re.IGNORECASE)

    # Remove hedging phrases common in conversational AI
    text = re.sub(r'\b(It appears that|It seems that|I think that|I believe that)\s+', '', text, flags=re.IGNORECASE)

    # Remove question-like structures
    text = re.sub(r'\bYou (should|could|might|may)\b', 'Consider', text, flags=re.IGNORECASE)
    text = re.sub(r'\byour (patient|case|clinical)\b', r'the \1', text, flags=re.IGNORECASE)

    return text.strip()


def _format_timestamp(ts: str | None) -> str:
    """Format timestamp for report header. Returns current time if None."""
    if ts:
        try:
            dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
            return dt.strftime('%B %d, %Y at %I:%M %p')
        except (ValueError, AttributeError):
            pass

    # Fallback to current time
    return datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p')


def _estimate_section_lines(lines: list[str]) -> int:
    """Estimate number of printed lines for a section."""
    return len(lines)


# ── Main Formatter Function ────────────────────────────────────────────────────

def format_clinical_report(
    original_query: str,
    response_text: str,
    test_recommendations: list[dict],
    citations_data: list[dict],
    confidence_score: int | None = None,
    timestamp: str | None = None,
) -> str:
    """
    Generate plain-text clinical report from AI Test Advisor outputs.

    Parameters
    ----------
    original_query : str
        The user's original clinical query
    response_text : str
        The narrative response text (may contain markdown)
    test_recommendations : list[dict]
        List of test recommendation objects with keys:
        - test_name (str)
        - test_code (str, optional)
        - rationale (str)
        - rank (str, optional)
        - specimen (str, optional)
        - tat (str, optional)
    citations_data : list[dict]
        List of citation objects with keys:
        - number (int)
        - source_type (str)
        - document (str)
        - excerpt (str, optional)
    confidence_score : int | None
        Confidence score (0-100), if available
    timestamp : str | None
        ISO timestamp of generation

    Returns
    -------
    str
        Formatted plain-text report ready for printing
    """

    output_lines = []
    sections = []  # Track sections for page-break calculation

    # ── SECTION 1: Header ──────────────────────────────────────────────────────
    header_lines = [
        '',
        _center_text('ARUP LABORATORIES'),
        _center_text('AI Test Advisor - Clinical Recommendation'),
        '',
        _center_text('Generated: ' + _format_timestamp(timestamp)),
        '',
        '=' * PAGE_WIDTH,
        '',
    ]
    output_lines.extend(header_lines)
    sections.append(('header', len(header_lines)))

    # ── SECTION 2: Query ───────────────────────────────────────────────────────
    query_lines = ['CLINICAL QUERY:', '']
    query_text = original_query.strip()
    # Indent query text as a block quote
    for line in _wrap_text(query_text, width=PAGE_WIDTH - 4, indent=4):
        query_lines.append(line)
    query_lines.extend(['', '-' * PAGE_WIDTH, ''])

    output_lines.extend(query_lines)
    sections.append(('query', len(query_lines)))

    # ── SECTION 3: Recommended Tests ───────────────────────────────────────────
    rec_lines = ['RECOMMENDED TESTS:', '']

    if test_recommendations:
        for idx, rec in enumerate(test_recommendations, start=1):
            test_name = rec.get('test_name', 'Unknown Test').strip()
            test_code = rec.get('test_code', '').strip()
            rationale = rec.get('rationale', '').strip()
            specimen = rec.get('specimen', '').strip()
            tat = rec.get('tat', '').strip()
            rank = rec.get('rank', '').strip()

            # Format test header
            test_header = f"{idx}. {test_name.upper()}"
            if test_code:
                test_header += f" (ARUP Code: {test_code})"
            rec_lines.append(test_header)

            # Add rank if present
            if rank:
                rec_lines.append(f"   Rank: {rank.capitalize()}")

            # Add rationale (cleaned of markdown and depersonalized)
            if rationale:
                clean_rationale = _depersonalize_text(_strip_markdown(rationale))
                for line in _wrap_text(clean_rationale, width=PAGE_WIDTH - 3, indent=3):
                    rec_lines.append(line)

            # Add specimen and TAT if available
            details = []
            if specimen:
                details.append(f"Specimen: {specimen}")
            if tat:
                details.append(f"TAT: {tat}")

            if details:
                rec_lines.append(f"   {' | '.join(details)}")

            rec_lines.append('')  # Blank line between tests
    else:
        rec_lines.append('   No specific test recommendations available.')
        rec_lines.append('')

    rec_lines.append('-' * PAGE_WIDTH)
    rec_lines.append('')

    output_lines.extend(rec_lines)
    sections.append(('recommendations', len(rec_lines)))

    # ── SECTION 4: Clinical Rationale ──────────────────────────────────────────
    rationale_lines = ['CLINICAL RATIONALE:', '']

    # Clean and depersonalize response text
    clean_response = _depersonalize_text(_strip_markdown(response_text))

    if clean_response:
        rationale_lines.extend(_wrap_text(clean_response, width=PAGE_WIDTH))
    else:
        rationale_lines.append('No additional clinical rationale provided.')

    rationale_lines.extend(['', '-' * PAGE_WIDTH, ''])

    output_lines.extend(rationale_lines)
    sections.append(('rationale', len(rationale_lines)))

    # ── PAGE BREAK DECISION ────────────────────────────────────────────────────
    # Calculate total lines so far
    current_line_count = sum(count for _, count in sections)

    # Estimate citation section size
    estimated_citation_lines = 5 + (len(citations_data) * 6)  # Conservative estimate

    # Insert page break before citations if content would exceed one page
    if current_line_count + estimated_citation_lines > LINES_PER_PAGE:
        output_lines.extend(['', '[PAGE BREAK]', ''])

    # ── SECTION 5: Reference Sources ───────────────────────────────────────────
    citation_lines = ['REFERENCE SOURCES:', '']

    if citations_data:
        for cit in citations_data:
            num = cit.get('number', '?')
            source_type = cit.get('source_type', 'General')
            document = cit.get('document', 'Unknown document').strip()
            excerpt = cit.get('excerpt', '').strip()

            # Citation header
            citation_lines.append(f"[{num}] {source_type}: {document}")

            # Add excerpt if available
            if excerpt:
                citation_lines.append('')
                for line in _wrap_text(excerpt, width=PAGE_WIDTH - 4, indent=4):
                    citation_lines.append(line)

            citation_lines.append('')  # Blank line between citations
    else:
        citation_lines.append('   No citations available.')
        citation_lines.append('')

    citation_lines.append('-' * PAGE_WIDTH)
    citation_lines.append('')

    output_lines.extend(citation_lines)
    sections.append(('citations', len(citation_lines)))

    # ── SECTION 6: Footer ──────────────────────────────────────────────────────
    footer_lines = []

    # Confidence score
    if confidence_score is not None:
        conf_text = f"Confidence Score: {confidence_score}/100"
        footer_lines.append(conf_text)
        footer_lines.append('')

    # Disclaimer
    footer_lines.append('DISCLAIMER:')
    footer_lines.append('')
    footer_lines.extend(_wrap_text(DISCLAIMER_TEXT, width=PAGE_WIDTH))
    footer_lines.append('')

    # Footer separator
    footer_lines.append('=' * PAGE_WIDTH)
    footer_lines.append(_center_text('End of Report'))
    footer_lines.append('')

    output_lines.extend(footer_lines)

    # ── FINAL OUTPUT ───────────────────────────────────────────────────────────
    return '\n'.join(output_lines)


# ── Export wrapper for integration ─────────────────────────────────────────────

def format_from_chat_response(data: dict) -> str:
    """
    Convenience wrapper that extracts fields from a /chat API response.

    Parameters
    ----------
    data : dict
        Complete /chat response object (frontend message bubble data)

    Returns
    -------
    str
        Formatted plain-text clinical report
    """
    # Extract response data
    answer = data.get('answer', '')
    recommendations = data.get('recommendations', [])
    citations = data.get('citations', [])

    # Extract metadata
    confidence_score = (data.get('confidence', {}) or {}).get('score')
    timestamp = data.get('timestamp')

    # Original query — try multiple fields as frontend may pass 'text' or 'query'
    # The query is typically in the previous user message, but frontend may include it
    original_query = (
        data.get('original_query') or
        data.get('query') or
        data.get('question') or
        data.get('text') or  # Frontend sometimes uses 'text' field
        'Clinical query not recorded'
    )

    return format_clinical_report(
        original_query=original_query,
        response_text=answer,
        test_recommendations=recommendations,
        citations_data=citations,
        confidence_score=confidence_score,
        timestamp=timestamp,
    )
